version: '3.8'
services:
  postgres:
    build:
      context: .
    image: "postgres-pdl"
    container_name: "postgres-pdl"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres-pdl
    volumes:
      - db-pdl:/data/postgres-pdl
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_DATABASE: postgresql
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    depends_on:
      - postgres

volumes:
  db-pdl:
    external: true