map:
  key: ${GMAPS_STATIC_API_KEY}
  url: "https://maps.googleapis.com"
  zoom: 18
  mapType: roadMap
  marker: ${CUSTOM_MARKER_SOURCE}
  size:
    height: 500
    width: 640

  details:
    url: "https://nominatim.openstreetmap.org"

springdoc:
  swagger-ui:
    path: /