map:
  key: ${GMAPS_STATIC_API_KEY}
  url: "https://maps.googleapis.com"
  zoom: 17
  mapType: roadMap
  marker: ${CUSTOM_MARKER_SOURCE}
  size:
    height: 420
    width: 640

reverse:
  datasource:
    nominatim:
      url: "https://nominatim.openstreetmap.org"

    openCage:
      key: "c6d1333f86ce4915a60d56c4f7ea0019"

    geoapify:
      url: "https://api.geoapify.com"

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true


springdoc:
  swagger-ui:
    path: /

logging:
  level:
    root: INFO
