map:
  key: ${GMAPS_STATIC_API_KEY}
  url: "https://maps.googleapis.com"
  zoom: 18
  mapType: roadMap
  marker: ${CUSTOM_MARKER_SOURCE}
  size:
    height: 500
    width: 640

reverse:
  datasource:
    nominatim:
      url: "https://nominatim.openstreetmap.org"
    openCage:
      key: "c6d1333f86ce4915a60d56c4f7ea0019"


springdoc:
  swagger-ui:
    path: /