map:
  key: ${GMAPS_STATIC_API_KEY}
  url: "https://maps.googleapis.com"
  zoom: 18
  mapType: roadMap
  marker: ${CUSTOM_MARKER_SOURCE}
  size:
    height: 500
    width: 640

reverse:
  datasource:
    nominatim:
      url: "https://nominatim.openstreetmap.org"
    openCage:
      key: "c6d1333f86ce4915a60d56c4f7ea0019"
    geoapify:
      url: "https://api.geoapify.com"

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog.yml

springdoc:
  swagger-ui:
    path: /
