map:
  key: ${GMAPS_STATIC_API_KEY}
  url: "https://maps.googleapis.com"
  zoom: 18
  mapType: roadMap
  marker: ${CUSTOM_MARKER_SOURCE}
  size:
    height: 420
    width: 640

reverse:
  datasource:
    nominatim:
      url: "https://nominatim.openstreetmap.org"

    openCage:
      key: "c6d1333f86ce4915a60d56c4f7ea0019"


springdoc:
  swagger-ui:
    path: /


#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: springuser
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
#    password: ThePassword
#  jpa:
#    hibernate:
#      ddl-auto: update
