server:
  port: 5000

spring:
  profiles:
    active: @spring.profiles.active@
  datasource:
    url: ${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

map:
  key: ${GMAPS_STATIC_API_KEY}
  url: "https://maps.googleapis.com"
  zoom: 17
  mapType: roadMap
  marker: ${CUSTOM_MARKER_SOURCE}
  size:
    height: 420
    width: 640

reverse:
  datasource:
    nominatim:
      url: "https://nominatim.openstreetmap.org"

    openCage:
      key: "c6d1333f86ce4915a60d56c4f7ea0019"

    geoapify:
      url: "https://api.geoapify.com"

springdoc:
  swagger-ui:
    path: /

logging:
  level:
    root: INFO
